### ISSUE TITLE
Simplification Bug

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyTheoremProver#140]
The following generates an exception:

```
define prop(bool r, int x, int y) is:
        r <==> (x <= y)

assert:
    forall(bool r, int x, int y):
        prop(x <= y,x,y)
```

The error trace produced is:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: cannot convert expression to atom: wyal.lang.WyalFile$Expr$LessThanOrEqual
	at wyal.commands.VerifyCommand.compile(VerifyCommand.java:254)
	at wyal.commands.VerifyCommand.execute(VerifyCommand.java:202)
	at wyal.commands.VerifyCommand.execute(VerifyCommand.java:1)
	at wycc.WyMain.main(WyMain.java:105)
Caused by: java.lang.IllegalArgumentException: cannot convert expression to atom: wyal.lang.WyalFile$Expr$LessThanOrEqual
	at wytp.proof.rules.Simplification.simplifyExpression(Simplification.java:436)
       ...
```

**Comment by DavePearce** [comment]
Ok, was relatively straightforward.
