### ISSUE TITLE
Counterexample Generation Internal Failure

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyTheoremProver#145]
The following causes a counterexample internal failure for reasons unknown:

```
type nat is (int n) where n >= 0

function sum(nat[] ns) -> (int r)
ensures r >= 0:
    //
    nat i = 0
    nat m = 0
    //
    while i < |ns|:
        m = m + ns[i]
        i = i - 1
    //
    return m
```

**Comment by DavePearce** [comment]
This generates the following exception trace:

```
java.lang.ClassCastException: wytp.proof.Formula$Quantifier cannot be cast to wyal.lang.WyalFile$Expr$UniversalQuantifier
	at wyal.util.Interpreter.evaluateExpression(Interpreter.java:154)
	at wyal.util.Interpreter.checkTypeInvariants(Interpreter.java:681)
	at wyal.util.Interpreter.evaluateForAll(Interpreter.java:124)
	...
```
